import type {
  Achievement,
  LeaderUser,
  Lesson,
  Subject,
  Test,
  User,
} from './types';

export const SUBJECTS: Subject[] = [
  {
    id: 'matematika',
    name: 'Matematika',
    short: 'Mat',
    icon: 'Sigma',
    color: '#a5b4fc',
    topics: 42,
    tests: 310,
  },
  {
    id: 'fizika',
    name: 'Fizika',
    short: 'Fiz',
    icon: 'Atom',
    color: '#7dd3fc',
    topics: 36,
    tests: 248,
  },
  {
    id: 'kimyo',
    name: 'Kimyo',
    short: 'Kim',
    icon: 'FlaskConical',
    color: '#86efac',
    topics: 30,
    tests: 196,
  },
  {
    id: 'biologiya',
    name: 'Biologiya',
    short: 'Bio',
    icon: 'Dna',
    color: '#fdba74',
    topics: 28,
    tests: 174,
  },
  {
    id: 'ona-tili',
    name: 'Ona tili',
    short: 'OT',
    icon: 'BookText',
    color: '#fda4af',
    topics: 24,
    tests: 158,
  },
  {
    id: 'ingliz-tili',
    name: 'Ingliz tili',
    short: 'Eng',
    icon: 'Languages',
    color: '#fcd34d',
    topics: 32,
    tests: 200,
  },
];

export const LESSONS: Lesson[] = [
  {
    id: 'mat-1',
    subject: 'matematika',
    title: 'Kvadrat tenglamalar',
    duration: 18,
    level: 'O‘rta',
    summary: 'Kvadrat tenglamani diskriminant orqali yechish va Viyet teoremasi.',
    content: [
      'Kvadrat tenglama ax² + bx + c = 0 ko‘rinishida bo‘ladi (a ≠ 0).',
      'Diskriminant D = b² − 4ac. D > 0 bo‘lsa ikkita yechim, D = 0 bo‘lsa bitta yechim, D < 0 bo‘lsa haqiqiy yechim yo‘q.',
      'Yechimlar: x = (−b ± √D) / 2a.',
      'Viyet teoremasi: x₁ + x₂ = −b/a, x₁·x₂ = c/a.',
    ],
    xp: 30,
  },
  {
    id: 'mat-2',
    subject: 'matematika',
    title: 'Progressiyalar',
    duration: 22,
    level: 'Yuqori',
    summary: 'Arifmetik va geometrik progressiya formulalari.',
    content: [
      'Arifmetik progressiya: aₙ = a₁ + (n−1)d.',
      'Arifmetik progressiya yig‘indisi: Sₙ = n(a₁ + aₙ)/2.',
      'Geometrik progressiya: bₙ = b₁ · qⁿ⁻¹.',
      'Cheksiz kamayuvchi GP yig‘indisi: S = b₁ / (1 − q), |q| < 1.',
    ],
    xp: 30,
  },
  {
    id: 'mat-3',
    subject: 'matematika',
    title: 'Trigonometriya asoslari',
    duration: 25,
    level: 'O‘rta',
    summary: 'Sinus, kosinus, tangens va asosiy ayniyatlar.',
    content: [
      'sin²α + cos²α = 1 — asosiy trigonometrik ayniyat.',
      'tg α = sin α / cos α, ctg α = cos α / sin α.',
      'Qo‘shish formulalari: sin(α±β) = sinα·cosβ ± cosα·sinβ.',
    ],
    xp: 30,
  },
  {
    id: 'fiz-1',
    subject: 'fizika',
    title: 'Nyutonning qonunlari',
    duration: 20,
    level: 'O‘rta',
    summary: 'Dinamikaning uchta asosiy qonuni va ularning qo‘llanilishi.',
    content: [
      '1-qonun (inersiya): tashqi kuch ta’sir qilmasa jism tinch yoki tekis to‘g‘ri chiziqli harakatda bo‘ladi.',
      '2-qonun: F = m·a.',
      '3-qonun: ta’sir va aks ta’sir teng hamda qarama-qarshi yo‘nalgan.',
    ],
    xp: 30,
  },
  {
    id: 'fiz-2',
    subject: 'fizika',
    title: 'Elektr toki',
    duration: 24,
    level: 'Yuqori',
    summary: 'Om qonuni, quvvat va Joul-Lens qonuni.',
    content: [
      'Om qonuni: I = U / R.',
      'Quvvat: P = U·I = I²·R.',
      'Joul-Lens qonuni: Q = I²·R·t.',
    ],
    xp: 30,
  },
  {
    id: 'kim-1',
    subject: 'kimyo',
    title: 'Atom tuzilishi',
    duration: 19,
    level: 'Boshlang‘ich',
    summary: 'Proton, neytron, elektron va elektron qavatlari.',
    content: [
      'Atom yadrosi protonlar va neytronlardan iborat.',
      'Tartib raqami = protonlar soni = elektronlar soni.',
      'Massa soni = protonlar + neytronlar.',
    ],
    xp: 30,
  },
  {
    id: 'kim-2',
    subject: 'kimyo',
    title: 'Kimyoviy reaksiyalar',
    duration: 21,
    level: 'O‘rta',
    summary: 'Reaksiya turlari va tenglamalarni tenglashtirish.',
    content: [
      'Birikish, parchalanish, o‘rin almashish va almashinish reaksiyalari.',
      'Massa saqlanish qonuni asosida tenglama tenglashtiriladi.',
    ],
    xp: 30,
  },
  {
    id: 'bio-1',
    subject: 'biologiya',
    title: 'Hujayra tuzilishi',
    duration: 17,
    level: 'Boshlang‘ich',
    summary: 'Hujayra organoidlari va ularning vazifalari.',
    content: [
      'Yadro — irsiy axborotni saqlaydi.',
      'Mitoxondriya — energiya (ATF) ishlab chiqaradi.',
      'Ribosoma — oqsil sintezi.',
    ],
    xp: 30,
  },
  {
    id: 'ot-1',
    subject: 'ona-tili',
    title: 'So‘z turkumlari',
    duration: 16,
    level: 'Boshlang‘ich',
    summary: 'Mustaqil va yordamchi so‘z turkumlari.',
    content: [
      'Mustaqil: ot, sifat, son, olmosh, fe’l, ravish.',
      'Yordamchi: ko‘makchi, bog‘lovchi, yuklama.',
    ],
    xp: 30,
  },
  {
    id: 'eng-1',
    subject: 'ingliz-tili',
    title: 'Present Tenses',
    duration: 23,
    level: 'O‘rta',
    summary: 'Present Simple, Continuous, Perfect farqlari.',
    content: [
      'Present Simple — doimiy/odat: I study every day.',
      'Present Continuous — hozir: I am studying now.',
      'Present Perfect — natija: I have studied this topic.',
    ],
    xp: 30,
  },
];

function q(
  id: string,
  text: string,
  options: string[],
  correct: number,
  explanation: string,
) {
  return { id, text, options, correct, explanation };
}

export const TESTS: Test[] = [
  {
    id: 'test-mat-1',
    subject: 'matematika',
    title: 'Kvadrat tenglamalar — sinov',
    difficulty: 'O‘rta',
    durationMin: 10,
    xp: 80,
    questions: [
      q(
        'm1',
        'x² − 5x + 6 = 0 tenglamaning ildizlari yig‘indisi nechaga teng?',
        ['5', '6', '−5', '1'],
        0,
        'Viyet teoremasiga ko‘ra x₁ + x₂ = −b/a = 5.',
      ),
      q(
        'm2',
        'D = b² − 4ac. Agar D < 0 bo‘lsa tenglama nechta haqiqiy ildizga ega?',
        ['2 ta', '1 ta', '0 ta', 'Cheksiz'],
        2,
        'Diskriminant manfiy bo‘lsa haqiqiy ildiz mavjud emas.',
      ),
      q(
        'm3',
        '2x² − 8 = 0 tenglamaning ildizlari:',
        ['±2', '±4', '2 va 0', '±√2'],
        0,
        'x² = 4, demak x = ±2.',
      ),
      q(
        'm4',
        'x² + 4x + 4 = 0 nechta ildizga ega?',
        ['2 ta', '1 ta (karrali)', '0 ta', '3 ta'],
        1,
        'D = 16 − 16 = 0, bitta karrali ildiz x = −2.',
      ),
      q(
        'm5',
        'x₁·x₂ = c/a formulasi qaysi teorema?',
        ['Pifagor', 'Viyet', 'Nyuton', 'Talesa'],
        1,
        'Bu Viyet teoremasining ikkinchi munosabati.',
      ),
    ],
  },
  {
    id: 'test-mat-2',
    subject: 'matematika',
    title: 'Progressiyalar — tezkor test',
    difficulty: 'Qiyin',
    durationMin: 8,
    xp: 90,
    questions: [
      q(
        'p1',
        'a₁ = 3, d = 4 bo‘lsa, a₅ nechaga teng?',
        ['19', '15', '23', '17'],
        0,
        'a₅ = 3 + 4·4 = 19.',
      ),
      q(
        'p2',
        'GP da b₁ = 2, q = 3 bo‘lsa b₄:',
        ['54', '18', '162', '24'],
        0,
        'b₄ = 2·3³ = 54.',
      ),
      q(
        'p3',
        'Cheksiz kamayuvchi GP yig‘indisi formulasi:',
        ['b₁/(1−q)', 'b₁·q', 'n(a₁+aₙ)/2', 'a₁+(n−1)d'],
        0,
        'S = b₁/(1−q), |q| < 1.',
      ),
    ],
  },
  {
    id: 'test-fiz-1',
    subject: 'fizika',
    title: 'Mexanika asoslari',
    difficulty: 'O‘rta',
    durationMin: 10,
    xp: 80,
    questions: [
      q(
        'f1',
        'Nyutonning 2-qonuni qaysi formula bilan ifodalanadi?',
        ['F = m·a', 'E = m·c²', 'P = U·I', 'Q = m·c·Δt'],
        0,
        'Kuch massa va tezlanish ko‘paytmasiga teng.',
      ),
      q(
        'f2',
        'Tezlik birligi (SI):',
        ['m/s', 'km', 'N', 'J'],
        0,
        'Tezlik metr bo‘lingan sekund (m/s).',
      ),
      q(
        'f3',
        'Erkin tushish tezlanishi taxminan:',
        ['9,8 m/s²', '5 m/s²', '20 m/s²', '1 m/s²'],
        0,
        'Yer yuzasida g ≈ 9,8 m/s².',
      ),
      q(
        'f4',
        'Inersiya qonuni — bu Nyutonning nechanchi qonuni?',
        ['1-qonun', '2-qonun', '3-qonun', 'Hech qaysi'],
        0,
        'Inersiya — Nyutonning birinchi qonuni.',
      ),
    ],
  },
  {
    id: 'test-fiz-2',
    subject: 'fizika',
    title: 'Elektr toki — sinov',
    difficulty: 'Qiyin',
    durationMin: 9,
    xp: 90,
    questions: [
      q(
        'e1',
        'Om qonuni formulasi:',
        ['I = U/R', 'U = I·R²', 'R = U·I', 'P = U/I'],
        0,
        'Tok kuchi kuchlanishni qarshilikka bo‘lganga teng.',
      ),
      q(
        'e2',
        'Quvvat formulasi:',
        ['P = U·I', 'P = U/R', 'P = I/U', 'P = R·t'],
        0,
        'P = U·I = I²·R.',
      ),
      q(
        'e3',
        'U = 12 V, R = 4 Ω. Tok kuchi I = ?',
        ['3 A', '48 A', '0,33 A', '8 A'],
        0,
        'I = U/R = 12/4 = 3 A.',
      ),
    ],
  },
  {
    id: 'test-kim-1',
    subject: 'kimyo',
    title: 'Atom va elementlar',
    difficulty: 'Oson',
    durationMin: 7,
    xp: 60,
    questions: [
      q(
        'k1',
        'Atomning tartib raqami nimani bildiradi?',
        ['Protonlar soni', 'Neytronlar soni', 'Massa', 'Zichlik'],
        0,
        'Tartib raqami = protonlar soni = elektronlar soni.',
      ),
      q(
        'k2',
        'Suv molekulasi formulasi:',
        ['H₂O', 'CO₂', 'O₂', 'NaCl'],
        0,
        'Suv — H₂O.',
      ),
      q(
        'k3',
        'Massa soni nimaga teng?',
        [
          'Proton + neytron',
          'Proton + elektron',
          'Faqat neytron',
          'Faqat elektron',
        ],
        0,
        'Massa soni = protonlar + neytronlar.',
      ),
    ],
  },
  {
    id: 'test-bio-1',
    subject: 'biologiya',
    title: 'Hujayra organoidlari',
    difficulty: 'Oson',
    durationMin: 6,
    xp: 60,
    questions: [
      q(
        'b1',
        'Energiya ishlab chiqaruvchi organoid:',
        ['Mitoxondriya', 'Ribosoma', 'Yadro', 'Vakuola'],
        0,
        'Mitoxondriya — hujayraning "energiya stansiyasi".',
      ),
      q(
        'b2',
        'Oqsil sintezi qayerda boradi?',
        ['Ribosoma', 'Yadro', 'Mitoxondriya', 'Membrana'],
        0,
        'Ribosomalarda oqsil sintez qilinadi.',
      ),
      q(
        'b3',
        'Irsiy axborot saqlanadigan organoid:',
        ['Yadro', 'Sitoplazma', 'Ribosoma', 'Lizosoma'],
        0,
        'Yadroda DNK — irsiy axborot saqlanadi.',
      ),
    ],
  },
  {
    id: 'test-ot-1',
    subject: 'ona-tili',
    title: 'So‘z turkumlari — sinov',
    difficulty: 'Oson',
    durationMin: 6,
    xp: 60,
    questions: [
      q(
        'o1',
        '"Kitob" so‘zi qaysi so‘z turkumiga mansub?',
        ['Ot', 'Sifat', 'Fe’l', 'Ravish'],
        0,
        'Predmet nomi — ot.',
      ),
      q(
        'o2',
        'Yordamchi so‘z turkumi qaysi?',
        ['Bog‘lovchi', 'Ot', 'Sifat', 'Son'],
        0,
        'Bog‘lovchi — yordamchi so‘z turkumi.',
      ),
      q(
        'o3',
        '"Tez yugurdi" da "tez" qaysi turkum?',
        ['Ravish', 'Ot', 'Olmosh', 'Fe’l'],
        0,
        'Harakat belgisini bildirgani uchun ravish.',
      ),
    ],
  },
  {
    id: 'test-eng-1',
    subject: 'ingliz-tili',
    title: 'Present Tenses Quiz',
    difficulty: 'O‘rta',
    durationMin: 8,
    xp: 70,
    questions: [
      q(
        'en1',
        'She ___ to school every day.',
        ['goes', 'go', 'going', 'gone'],
        0,
        'Present Simple, 3-shaxs birlik: goes.',
      ),
      q(
        'en2',
        'Look! The baby ___ now.',
        ['is sleeping', 'sleeps', 'slept', 'sleep'],
        0,
        'Hozirgi davom etayotgan harakat — Present Continuous.',
      ),
      q(
        'en3',
        'I ___ already finished my homework.',
        ['have', 'has', 'had', 'having'],
        0,
        'Present Perfect: have finished.',
      ),
      q(
        'en4',
        'They ___ football on Sundays.',
        ['play', 'plays', 'playing', 'played'],
        0,
        'Present Simple ko‘plik: play.',
      ),
    ],
  },
];

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'a-first',
    title: 'Birinchi qadam',
    description: 'Birinchi testni yakunlash',
    icon: 'Footprints',
    color: '#a5b4fc',
    requirement: 1,
    metric: 'tests',
  },
  {
    id: 'a-tests10',
    title: 'Test ustasi',
    description: '10 ta test yechish',
    icon: 'ClipboardCheck',
    color: '#7dd3fc',
    requirement: 10,
    metric: 'tests',
  },
  {
    id: 'a-tests50',
    title: 'Marafonchi',
    description: '50 ta test yechish',
    icon: 'Trophy',
    color: '#fcd34d',
    requirement: 50,
    metric: 'tests',
  },
  {
    id: 'a-streak3',
    title: 'Olov boshlanishi',
    description: '3 kunlik seriya',
    icon: 'Flame',
    color: '#fdba74',
    requirement: 3,
    metric: 'streak',
  },
  {
    id: 'a-streak7',
    title: 'Haftalik olov',
    description: '7 kunlik seriya',
    icon: 'Flame',
    color: '#fda4af',
    requirement: 7,
    metric: 'streak',
  },
  {
    id: 'a-streak30',
    title: 'Buzilmas odat',
    description: '30 kunlik seriya',
    icon: 'CalendarCheck',
    color: '#86efac',
    requirement: 30,
    metric: 'streak',
  },
  {
    id: 'a-xp1000',
    title: 'Ming yulduz',
    description: '1000 XP to‘plash',
    icon: 'Star',
    color: '#fcd34d',
    requirement: 1000,
    metric: 'xp',
  },
  {
    id: 'a-xp5000',
    title: 'XP magnati',
    description: '5000 XP to‘plash',
    icon: 'Sparkles',
    color: '#c4b5fd',
    requirement: 5000,
    metric: 'xp',
  },
  {
    id: 'a-level10',
    title: '10-darajaga chiqish',
    description: '10-levelga yetish',
    icon: 'TrendingUp',
    color: '#a5b4fc',
    requirement: 10,
    metric: 'level',
  },
  {
    id: 'a-lessons10',
    title: 'Bilim izlovchi',
    description: '10 ta darsni yakunlash',
    icon: 'GraduationCap',
    color: '#7dd3fc',
    requirement: 10,
    metric: 'lessons',
  },
  {
    id: 'a-perfect',
    title: 'Mukammallik',
    description: 'Testni 100% to‘g‘ri yechish',
    icon: 'Target',
    color: '#86efac',
    requirement: 1,
    metric: 'perfect',
  },
  {
    id: 'a-perfect5',
    title: 'Aniq nishonchi',
    description: '5 ta testni 100% yechish',
    icon: 'Crosshair',
    color: '#fda4af',
    requirement: 5,
    metric: 'perfect',
  },
];

export const LEADERBOARD: LeaderUser[] = [
  { id: 'l1', name: 'Sardor Aliyev', xp: 9450, level: 14, streak: 41, region: 'Toshkent', avatarColor: '#a5b4fc' },
  { id: 'l2', name: 'Malika Yusupova', xp: 8720, level: 13, streak: 33, region: 'Samarqand', avatarColor: '#fda4af' },
  { id: 'l3', name: 'Asadbek Tursunov', xp: 7980, level: 12, streak: 28, region: 'Andijon', avatarColor: '#86efac' },
  { id: 'l4', name: 'Sevinch Mahmudova', xp: 7410, level: 12, streak: 22, region: 'Farg‘ona', avatarColor: '#fcd34d' },
  { id: 'l5', name: 'Jasur Qodirov', xp: 6890, level: 11, streak: 19, region: 'Buxoro', avatarColor: '#7dd3fc' },
  { id: 'l6', name: 'Dilnoza Islomova', xp: 6240, level: 11, streak: 25, region: 'Namangan', avatarColor: '#c4b5fd' },
  { id: 'l7', name: 'Bekzod Rasulov', xp: 5710, level: 10, streak: 14, region: 'Qashqadaryo', avatarColor: '#fdba74' },
  { id: 'l8', name: 'Nodira Saidova', xp: 5180, level: 10, streak: 17, region: 'Xorazm', avatarColor: '#a5b4fc' },
  { id: 'l9', name: 'Otabek Yo‘ldoshev', xp: 4630, level: 9, streak: 11, region: 'Navoiy', avatarColor: '#86efac' },
  { id: 'l10', name: 'Madina Olimova', xp: 4120, level: 9, streak: 9, region: 'Surxondaryo', avatarColor: '#fda4af' },
  { id: 'l11', name: 'Shahzod Ergashev', xp: 3580, level: 8, streak: 7, region: 'Jizzax', avatarColor: '#7dd3fc' },
  { id: 'l12', name: 'Gulnoza Tosheva', xp: 3010, level: 7, streak: 6, region: 'Sirdaryo', avatarColor: '#fcd34d' },
];

function baseProgress(): Record<string, number> {
  return {
    matematika: 75,
    'ona-tili': 80,
    adabiyot: 68,
    tarix: 62,
    fizika: 0,
    kimyo: 0,
    biologiya: 0,
    'ingliz-tili': 0,
  };
}

export const DEMO_USERS: User[] = [
  {
    id: 'u-saydalixon',
    name: 'Saydalixon Islomov',
    email: 'saydalixon@demo.uz',
    region: 'Toshkent',
    grade: '11-sinf',
    avatarColor: '#a5b4fc',
    plan: 'Premium',
    xp: 1250,
    streak: 15,
    lastActiveISO: new Date(Date.now() - 86400000).toISOString().slice(0, 10),
    dailyGoal: 5,
    dailyDone: 2,
    completedLessons: ['mat-1', 'fiz-1'],
    results: [
      {
        id: 'r1',
        testId: 'test-mat-1',
        subject: 'matematika',
        title: 'Kvadrat tenglamalar — sinov',
        total: 5,
        correct: 4,
        xp: 73,
        dateISO: new Date(Date.now() - 2 * 86400000).toISOString(),
      },
      {
        id: 'r2',
        testId: 'test-fiz-1',
        subject: 'fizika',
        title: 'Mexanika asoslari',
        total: 4,
        correct: 4,
        xp: 98,
        dateISO: new Date(Date.now() - 86400000).toISOString(),
      },
    ],
    subjectProgress: baseProgress() as User['subjectProgress'],
    lives: 10, livesMax: 10, livesResetISO: new Date().toISOString().slice(0,10), consecutiveCorrect: 0,
    coins: 320,
    gems: 5,
    joinedISO: '2024-11-02',
    placementLevel: 'O‘rta',
    dailyMinutes: 30,
    weakSubjects: ['adabiyot', 'tarix'],
  },
  {
    id: 'u-sevinch',
    name: 'Sevinch Mahmudova',
    email: 'sevinch@demo.uz',
    region: 'Farg‘ona',
    grade: '11-sinf',
    avatarColor: '#fcd34d',
    plan: 'Premium+',
    xp: 7410,
    streak: 22,
    lastActiveISO: new Date(Date.now() - 86400000).toISOString().slice(0, 10),
    dailyGoal: 6,
    dailyDone: 4,
    completedLessons: ['mat-1', 'mat-2', 'fiz-1', 'kim-1', 'bio-1'],
    results: [],
    subjectProgress: {
      matematika: 88,
      'ona-tili': 92,
      adabiyot: 74,
      tarix: 70,
      fizika: 0,
      kimyo: 0,
      biologiya: 0,
      'ingliz-tili': 0,
    },
    lives: 8, livesMax: 10, livesResetISO: new Date().toISOString().slice(0,10), consecutiveCorrect: 2,
    coins: 1240,
    gems: 20,
    joinedISO: '2024-09-15',
    placementLevel: 'O‘rta',
    dailyMinutes: 45,
    weakSubjects: ['matematika'],
  },
  {
    id: 'u-asadbek',
    name: 'Asadbek Tursunov',
    email: 'asadbek@demo.uz',
    region: 'Andijon',
    grade: 'Abituriyent',
    avatarColor: '#86efac',
    plan: 'Bepul',
    xp: 7980,
    streak: 28,
    lastActiveISO: new Date(Date.now() - 86400000).toISOString().slice(0, 10),
    dailyGoal: 5,
    dailyDone: 1,
    completedLessons: ['mat-1', 'fiz-1', 'fiz-2'],
    results: [],
    subjectProgress: {
      matematika: 82,
      'ona-tili': 76,
      adabiyot: 71,
      tarix: 85,
      fizika: 0,
      kimyo: 0,
      biologiya: 0,
      'ingliz-tili': 0,
    },
    lives: 10, livesMax: 10, livesResetISO: new Date().toISOString().slice(0,10), consecutiveCorrect: 0,
    coins: 540,
    gems: 10,
    joinedISO: '2024-08-20',
    placementLevel: 'O‘rta',
    dailyMinutes: 60,
    weakSubjects: ['ona-tili', 'adabiyot'],
  },
];

export function freshUser(
  name: string,
  email: string,
  region: string,
  grade: string,
): User {
  const colors = ['#a5b4fc', '#7dd3fc', '#86efac', '#fdba74', '#fda4af', '#fcd34d'];
  return {
    id: 'u-' + Math.random().toString(36).slice(2, 9),
    name,
    email,
    region,
    grade,
    avatarColor: colors[Math.floor(Math.random() * colors.length)],
    plan: 'Bepul',
    xp: 0,
    streak: 0,
    lastActiveISO: '',
    dailyGoal: 5,
    dailyDone: 0,
    completedLessons: [],
    results: [],
    subjectProgress: {
      matematika: 0,
      'ona-tili': 0,
      adabiyot: 0,
      tarix: 0,
      fizika: 0,
      kimyo: 0,
      biologiya: 0,
      'ingliz-tili': 0,
    },
    lives: 10, livesMax: 10, livesResetISO: new Date().toISOString().slice(0,10), consecutiveCorrect: 0,
    coins: 0,
    gems: 0,
    joinedISO: new Date().toISOString().slice(0, 10),
  };
}

export function subjectById(id: string) {
  return SUBJECTS.find((s) => s.id === id)!;
}
