# Generated by Django 5.0.6 on 2026-05-23 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='challenge',
            new_name='friends_cha_challen_9c8eb6_idx',
            old_name='friends_ch_challen_a83b71_idx',
        ),
        migrations.RenameIndex(
            model_name='challenge',
            new_name='friends_cha_opponen_09cd89_idx',
            old_name='friends_ch_opponen_7f1e84_idx',
        ),
        migrations.RenameIndex(
            model_name='friendship',
            new_name='friends_fri_from_us_367ff9_idx',
            old_name='friends_fr_from_us_2c0e2f_idx',
        ),
        migrations.RenameIndex(
            model_name='friendship',
            new_name='friends_fri_to_user_1e5be9_idx',
            old_name='friends_fr_to_user_b1c7a5_idx',
        ),
    ]
