# Generated by Django 5.0.6 on 2026-05-23 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duels', '0002_duel_match_arena'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='duelmatch',
            new_name='duels_duelm_challen_de1e5f_idx',
            old_name='duels_duelm_challen_idx',
        ),
        migrations.RenameIndex(
            model_name='duelmatch',
            new_name='duels_duelm_opponen_6e09ea_idx',
            old_name='duels_duelm_opponen_idx',
        ),
    ]
