# Generated by Django 5.0.6 on 2026-05-23 09:21

import apps.users.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_coins'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.users.managers.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='daily_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='placement_level',
            field=models.CharField(blank=True, choices=[('Boshlang‘ich', 'Boshlang‘ich'), ('O‘rta', 'O‘rta'), ('Yuqori', 'Yuqori')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='weak_subjects',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
