# Generated by Django 5.0.6 on 2026-05-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers_user_daily_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gems',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
