# Generated by Django 5.0.6 on 2026-05-23 09:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreSubject',
            fields=[
                ('id', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('short', models.CharField(max_length=24)),
                ('icon', models.CharField(default='BookOpen', max_length=40)),
                ('color', models.CharField(default='#2563eb', max_length=9)),
                ('is_required', models.BooleanField(default=True)),
                ('coming_soon', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CoreTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('question_limit', models.PositiveSmallIntegerField(default=5)),
                ('xp_per_correct', models.PositiveSmallIntegerField(default=12)),
                ('pass_bonus_xp', models.PositiveSmallIntegerField(default=20)),
                ('perfect_bonus_xp', models.PositiveSmallIntegerField(default=40)),
                ('coin_reward', models.PositiveSmallIntegerField(default=3)),
                ('gem_reward_perfect', models.PositiveSmallIntegerField(default=2)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoreTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('correct_index', models.PositiveSmallIntegerField(default=0)),
                ('explanation', models.TextField(blank=True)),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core_learning.coretest')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GradeTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(choices=[(5, '5-sinf'), (6, '6-sinf'), (7, '7-sinf'), (8, '8-sinf'), (9, '9-sinf'), (10, '10-sinf'), (11, '11-sinf')])),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core_learning.coresubject')),
            ],
            options={
                'ordering': ['subject__order', 'grade'],
                'unique_together': {('subject', 'grade')},
            },
        ),
        migrations.CreateModel(
            name='LearningUnit',
            fields=[
                ('id', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('summary', models.TextField(blank=True)),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core_learning.gradetrack')),
            ],
            options={
                'ordering': ['track__subject__order', 'track__grade', 'order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='coretest',
            name='unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='core_learning.learningunit'),
        ),
        migrations.CreateModel(
            name='CoreAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('audio', 'Audio'), ('practice', 'Practice'), ('test', 'Test')], max_length=16)),
                ('total', models.PositiveSmallIntegerField(default=0)),
                ('correct', models.PositiveSmallIntegerField(default=0)),
                ('wrong_question_ids', models.JSONField(blank=True, default=list)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('xp_earned', models.PositiveSmallIntegerField(default=0)),
                ('coins_earned', models.PositiveSmallIntegerField(default=0)),
                ('gems_earned', models.PositiveSmallIntegerField(default=0)),
                ('hearts_lost', models.PositiveSmallIntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_complete', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_attempts', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core_learning.learningunit')),
            ],
            options={
                'ordering': ['-finished_at'],
            },
        ),
        migrations.CreateModel(
            name='AudioLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('audio_url', models.URLField(blank=True, default='')),
                ('transcript', models.TextField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(default=300)),
                ('xp_reward', models.PositiveSmallIntegerField(default=10)),
                ('coin_reward', models.PositiveSmallIntegerField(default=1)),
                ('gem_reward', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='core_learning.learningunit')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('game_type', models.CharField(choices=[('quiz', 'Quiz'), ('match', 'Match'), ('drag_drop', 'Drag & drop')], default='quiz', max_length=20)),
                ('xp_per_correct', models.PositiveSmallIntegerField(default=8)),
                ('coin_reward', models.PositiveSmallIntegerField(default=2)),
                ('gem_reward_perfect', models.PositiveSmallIntegerField(default=1)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practice', to='core_learning.learningunit')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('question_type', models.CharField(default='quiz', max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.JSONField(default=dict)),
                ('explanation', models.TextField(blank=True)),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core_learning.practicegame')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_daily_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CoreProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_completed', models.BooleanField(default=False)),
                ('practice_completed', models.BooleanField(default=False)),
                ('test_completed', models.BooleanField(default=False)),
                ('best_practice_score', models.PositiveSmallIntegerField(default=0)),
                ('best_test_score', models.PositiveSmallIntegerField(default=0)),
                ('total_xp_earned', models.PositiveIntegerField(default=0)),
                ('total_coins_earned', models.PositiveIntegerField(default=0)),
                ('total_gems_earned', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_progress', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_rows', to='core_learning.learningunit')),
            ],
            options={
                'ordering': ['unit__track__subject__order', 'unit__track__grade'],
                'unique_together': {('user', 'unit')},
            },
        ),
        migrations.CreateModel(
            name='AiLearningSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField()),
                ('source', models.CharField(choices=[('practice', 'Practice'), ('test', 'Test'), ('audio', 'Audio')], max_length=16)),
                ('question_model', models.CharField(blank=True, default='', max_length=40)),
                ('question_id', models.CharField(blank=True, default='', max_length=64)),
                ('is_correct', models.BooleanField(default=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_signals', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_signals', to='core_learning.coresubject')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_signals', to='core_learning.learningunit')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'subject', 'is_correct'], name='core_learni_user_id_b6c25d_idx'), models.Index(fields=['user', 'created_at'], name='core_learni_user_id_b80b9d_idx')],
            },
        ),
    ]
